# Generated by Django 2.2.2 on 2021-04-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_management', '0002_auto_20210406_2054'),
    ]

    operations = [
    ]
